"""The built-in observation fields, one module per kind of quantity.

- :mod:`.ownship` - position, heading, altitude and speeds
- :mod:`.autopilot` - the autopilot's selections and the error from each
- :mod:`.performance` - capability descriptors and the flight phase
- :mod:`.route` - the aircraft's own route fixes
- :mod:`.intruders` - each intruder relative to the ownship
- :mod:`.conflict` - conflict detection and geometry, per intruder
- :mod:`.episode` - time in the environment and the previous action
- :mod:`.transforms` - fields built from other fields
- :mod:`.queryable` - fields read from a queryable the scenario configures
  (a named waypoint or region); these declare the queryable they need

Every field is importable from here, whichever module defines it.
"""

from __future__ import annotations

from ..base import ObsField, ObsMeta, ObsQuantity, PairObsField, Unit
from .autopilot import (
    ApAltErrorFt,
    ApAltErrorM,
    ApAltFt,
    ApAltM,
    ApCasErrorKts,
    ApCasKts,
    ApCasMs,
    ApHdgDeg,
    ApHdgErrorDeg,
    ApLnavVnavOn,
)
from .conflict import (
    ConflictHorizontalDistAtCpaNm,
    ConflictHorizontalSepAtCpaNm,
    ConflictRisk,
    ConflictSignedVerticalSepAtEntryFt,
    ConflictTcpaS,
    ConflictTlosS,
    ConflictVerticalSepAtCpaFt,
    InConf,
    InLosNow,
)
from .episode import (
    PrevActionNorm,
    TimeInEnvS,
)
from .intruders import (
    BearingRateDegPerSec,
    BrgFromOwnDeg,
    BrgFromOwnRelTrkDeg,
    ClosingRateKts,
    DistToOwnNm,
    HorizontalDistAtCpaNm,
    IntruderCommMessage,
    IntruderFixApproachDistNm,
    IntruderFixArrivalDeltaS,
    IntruderFixVerticalSepFt,
    RelPosAlongTrackNm,
    RelPosAtCpaAlongTrackNm,
    RelPosAtCpaCrossTrackNm,
    RelPosCrossTrackNm,
    RelVelAlongTrackKts,
    RelVelCrossTrackKts,
    RelVsFtMin,
    TcpaS,
    TlosS,
    VerticalSepAtCpaFt,
)
from .ownship import (
    AltFt,
    AltM,
    AxMs2,
    CasKts,
    CasMs,
    CrossoverAltMarginFt,
    GsKts,
    GsMs,
    HdgDeg,
    LatDeg,
    LonDeg,
    MachNumber,
    TasKts,
    TasMs,
    TrkDeg,
    VsFtMin,
    VsMs,
)
from .performance import (
    FlightPhaseOneHot,
    MtowT,
    PerfCeilingFt,
    PerfMassT,
    PerfVmaxKts,
    PerfVminKts,
    PerfVsMaxFtMin,
    PerfVsMinFtMin,
    TurnRadiusNm,
)
from .queryable import (
    ActiveWaypointAltDiffFt,
    ActiveWaypointAvailable,
    ActiveWaypointBearingDeg,
    ActiveWaypointDistanceNm,
    ActiveWaypointObsField,
    ActiveWaypointOneHot,
    ActiveWaypointRouteIndex,
    ActiveWaypointTrackErrorDeg,
    QueryableObsField,
    QueryRegionInside,
    QueryRegionInsideDuringStep,
    QueryRegionInsideTimeTotalS,
    WaypointAltDiffFt,
    WaypointBearingDeg,
    WaypointDistanceNm,
    WaypointMinDistanceNm,
    WaypointResultObsField,
    WaypointRouteActive,
    WaypointRouteFuture,
    WaypointRouteIndex,
    WaypointRouteReached,
    WaypointSatisfied,
    WaypointSatisfiedDuringStep,
    WaypointSatisfiedTimeTotalS,
    WaypointTrackErrorDeg,
)
from .route import (
    ActiveRouteWaypointAltDiffFt,
    ActiveRouteWaypointBearingDeg,
    ActiveRouteWaypointDistanceNm,
    ActiveRouteWaypointEteS,
    ActiveRouteWaypointHasAltConstraint,
    ActiveRouteWaypointHasSpdConstraint,
    ActiveRouteWaypointSpdDiffKts,
    ActiveRouteWaypointSpdErrorCrossover,
    ActiveRouteWaypointTrackErrorDeg,
    ActiveRouteWaypointValid,
    ActiveRouteWaypointVerticalEteS,
)
from .transforms import (
    AngleDifference,
    Difference,
    LaggedObs,
    LaggedPair,
)

__all__ = [
    "ObsField",
    "ObsMeta",
    "ObsQuantity",
    "PairObsField",
    "Unit",
    "LatDeg",
    "LonDeg",
    "HdgDeg",
    "TrkDeg",
    "AltFt",
    "AltM",
    "CasKts",
    "CasMs",
    "TasKts",
    "TasMs",
    "VsFtMin",
    "VsMs",
    "AxMs2",
    "MachNumber",
    "CrossoverAltMarginFt",
    "GsKts",
    "GsMs",
    "ApHdgDeg",
    "ApCasKts",
    "ApCasMs",
    "ApAltFt",
    "ApAltM",
    "ApLnavVnavOn",
    "ApHdgErrorDeg",
    "ApCasErrorKts",
    "ApAltErrorFt",
    "ApAltErrorM",
    "PerfVminKts",
    "PerfVmaxKts",
    "PerfVsMaxFtMin",
    "PerfVsMinFtMin",
    "PerfCeilingFt",
    "PerfMassT",
    "TurnRadiusNm",
    "MtowT",
    "FlightPhaseOneHot",
    "ActiveRouteWaypointDistanceNm",
    "ActiveRouteWaypointBearingDeg",
    "ActiveRouteWaypointTrackErrorDeg",
    "ActiveRouteWaypointValid",
    "ActiveRouteWaypointHasAltConstraint",
    "ActiveRouteWaypointHasSpdConstraint",
    "ActiveRouteWaypointAltDiffFt",
    "ActiveRouteWaypointSpdDiffKts",
    "ActiveRouteWaypointSpdErrorCrossover",
    "ActiveRouteWaypointEteS",
    "ActiveRouteWaypointVerticalEteS",
    "DistToOwnNm",
    "TcpaS",
    "TlosS",
    "ClosingRateKts",
    "BearingRateDegPerSec",
    "RelPosAlongTrackNm",
    "RelPosCrossTrackNm",
    "RelVelAlongTrackKts",
    "RelVelCrossTrackKts",
    "RelPosAtCpaAlongTrackNm",
    "RelPosAtCpaCrossTrackNm",
    "RelVsFtMin",
    "HorizontalDistAtCpaNm",
    "VerticalSepAtCpaFt",
    "IntruderFixApproachDistNm",
    "IntruderFixArrivalDeltaS",
    "IntruderFixVerticalSepFt",
    "IntruderCommMessage",
    "BrgFromOwnDeg",
    "BrgFromOwnRelTrkDeg",
    "ConflictHorizontalDistAtCpaNm",
    "ConflictVerticalSepAtCpaFt",
    "ConflictHorizontalSepAtCpaNm",
    "ConflictSignedVerticalSepAtEntryFt",
    "ConflictTcpaS",
    "ConflictTlosS",
    "InConf",
    "InLosNow",
    "ConflictRisk",
    "TimeInEnvS",
    "PrevActionNorm",
    "LaggedObs",
    "LaggedPair",
    "Difference",
    "AngleDifference",
    "QueryableObsField",
    "WaypointResultObsField",
    "ActiveWaypointObsField",
    "QueryRegionInside",
    "QueryRegionInsideDuringStep",
    "QueryRegionInsideTimeTotalS",
    "WaypointDistanceNm",
    "WaypointBearingDeg",
    "WaypointTrackErrorDeg",
    "WaypointAltDiffFt",
    "WaypointRouteIndex",
    "WaypointRouteActive",
    "WaypointRouteReached",
    "WaypointRouteFuture",
    "WaypointSatisfied",
    "WaypointSatisfiedDuringStep",
    "WaypointSatisfiedTimeTotalS",
    "WaypointMinDistanceNm",
    "ActiveWaypointAvailable",
    "ActiveWaypointRouteIndex",
    "ActiveWaypointOneHot",
    "ActiveWaypointDistanceNm",
    "ActiveWaypointBearingDeg",
    "ActiveWaypointAltDiffFt",
    "ActiveWaypointTrackErrorDeg",
]
